db:
  username: ${username.value:postgres}
  password: postgres
  driver: PostgresDriver
  url: postgres:5432
  hosts=: localhost,127.0.0.1
  properties:
    first: 123
    second: 567
    third: Third
  pool:
  size: 12
  timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3

spring.profiles.active: qa
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: validate


logging:
  level:
    root: info
    org.example.spring.database.pool: info
  file:
    name: Starter.log
    path: /
